# Generated by Django 4.0.1 on 2022-07-15 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('user_email', models.EmailField(max_length=500)),
                ('user_name', models.CharField(blank=True, default='None', max_length=500, null=True)),
                ('ip_address', models.CharField(max_length=500)),
                ('activity', models.CharField(max_length=500)),
                ('country', models.CharField(default='None', max_length=500)),
            ],
            options={
                'ordering': ('-date', '-time'),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('language', models.CharField(choices=[('en-us', 'English'), ('fr', 'French')], default='en-us', max_length=5)),
                ('country', models.CharField(choices=[('HQ', 'HQ'), ('KE', 'KE'), ('ZW', 'ZW'), ('NG', 'NG'), ('TN', 'TN'), ('GH', 'GH'), ('CIV', 'CIV')], max_length=60)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
