# Generated by Django 4.0.1 on 2022-12-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreviewApp', '0002_paymentadvice_narration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentadvice',
            name='Narration',
        ),
        migrations.AddField(
            model_name='technical',
            name='Narration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
