# Generated by Django 4.0.1 on 2022-08-01 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CounterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Counter', models.IntegerField()),
                ('Company', models.CharField(blank=True, max_length=500, null=True)),
                ('Counterdate', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrontEndReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReceiptName', models.CharField(blank=True, max_length=500, null=True)),
                ('HashedDate', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReceiptNumber', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MappedTechnical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(blank=True, choices=[('Non-Paired', 'Non-Paired'), ('Paired', 'Paired')], default='Paired', max_length=20, null=True)),
                ('Category', models.CharField(blank=True, max_length=500, null=True)),
                ('Purpose', models.CharField(blank=True, max_length=500, null=True)),
                ('Doclanguage', models.CharField(blank=True, max_length=500, null=True)),
                ('WorkSheetId', models.CharField(blank=True, max_length=500, null=True)),
                ('BusinessPartner', models.CharField(blank=True, max_length=500, null=True)),
                ('ReceiptNumber', models.CharField(blank=True, max_length=500, null=True)),
                ('Currency', models.CharField(blank=True, max_length=500, null=True)),
                ('Amount', models.CharField(blank=True, max_length=500, null=True)),
                ('BalanceUnsettledAmount', models.CharField(blank=True, max_length=500, null=True)),
                ('PaymentType', models.CharField(blank=True, max_length=500, null=True)),
                ('Office', models.CharField(blank=True, max_length=500, null=True)),
                ('MailSubject', models.CharField(blank=True, max_length=200, null=True)),
                ('MailBody', models.TextField(blank=True, null=True)),
                ('ReceiverEmail', models.CharField(blank=True, max_length=1000, null=True)),
                ('SendStatus', models.BooleanField(blank=True, null=True)),
                ('IssuedBy', models.CharField(blank=True, max_length=500, null=True)),
                ('ValueDate', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('MailDate', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'ordering': ['-ReceiptNumber'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReceiptNumber', models.TextField(blank=True, max_length=500, null=True)),
                ('BusinessTitle', models.TextField(blank=True, max_length=500, null=True)),
                ('ResponsiblePartner', models.TextField(blank=True, max_length=500, null=True)),
                ('BalanceClassofBusiness', models.TextField(blank=True, max_length=500, null=True)),
                ('LevelofBusiness', models.TextField(blank=True, max_length=500, null=True)),
                ('TypeofBusiness', models.TextField(blank=True, max_length=500, null=True)),
                ('Currency', models.TextField(blank=True, max_length=500, null=True)),
                ('Amount', models.TextField(blank=True, max_length=500, null=True)),
                ('Claimid', models.CharField(blank=True, max_length=500, null=True)),
                ('Claimname', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(blank=True, choices=[('Non-Paired', 'Non-Paired'), ('Paired', 'Paired')], default='Non-Paired', max_length=20, null=True)),
                ('Category', models.CharField(blank=True, max_length=500, null=True)),
                ('PaymentPartner', models.CharField(blank=True, max_length=500, null=True)),
                ('BankID', models.CharField(blank=True, max_length=500, null=True)),
                ('BankName', models.CharField(blank=True, max_length=500, null=True)),
                ('BankAccountNo', models.CharField(blank=True, max_length=500, null=True)),
                ('BankAccountCurrencyCode', models.CharField(blank=True, max_length=500, null=True)),
                ('OriginalCurrencyCode', models.CharField(blank=True, max_length=500, null=True)),
                ('BalanceOriginal', models.CharField(blank=True, max_length=500, null=True)),
                ('BalanceOutstandingOriginal', models.CharField(blank=True, max_length=500, null=True)),
                ('RemittanceDirection', models.CharField(blank=True, max_length=500, null=True)),
                ('RemittanceStatus', models.CharField(blank=True, max_length=500, null=True)),
                ('Company', models.CharField(blank=True, max_length=500, null=True)),
                ('ReceiptNumber', models.CharField(blank=True, max_length=500)),
                ('ReceiverEmail', models.CharField(blank=True, max_length=1000, null=True)),
                ('MailSubject', models.CharField(blank=True, max_length=200, null=True)),
                ('MailBody', models.TextField(blank=True, null=True)),
                ('SendStatus', models.BooleanField(blank=True, null=True)),
                ('ValueDate', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('IssuedBy', models.CharField(blank=True, max_length=500, null=True)),
                ('MailDate', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'ordering': ['-ReceiptNumber'],
            },
        ),
    ]
